### ISSUE TITLE
V4 is out list the features already!

### ISSUE THREAD

**Issue by XTeamXeno** [QmelZ/Hackustry#13]
Just do it!

**Comment by QmelZ** [comment]
amazing

how is v4 out, i didnt even release it yet

**Comment by BlueWolf3682** [comment]
![Screenshot_20210117-154850](https://user-images.githubusercontent.com/61173114/104858344-8fe28000-58db-11eb-90bf-6f114f6eddd4.png)



pretty sure this says v3.3
