### ISSUE TITLE
uhh i dont think it works in 127.1 cause its not showing up in multiplayer nor campaign

### ISSUE THREAD

**Issue by C0D3Giant** [QmelZ/hackustry#18]
it  aint showing up in 127.1 so you havent updated this yet?

**Comment by QmelZ** [comment]
the mod is updated, and works fine on 127.1 on my devices. i might possibly be able to fix it if you provide your last_log with the mod enabled.

**Comment by QmelZ** [comment]
*wrong button lol*

**Comment by C0D3Giant** [comment]
uhh i cant the log. is it a file or a in-game log i can use using developer mode

**Comment by QmelZ** [comment]
it's a file called `last_log.txt`

**Comment by SMOLKEYS** [comment]
Android > data > io.anuke.mindustry > files > last_log.txt

**Comment by C0D3Giant** [comment]
im using pc

**Comment by QmelZ** [comment]
on windows, `C:\Users\<username>\AppData\Roaming\Mindustry\last_log.txt`
on linux, `~/.local/share/Mindustry/last_log.txt`
i don't know how to access it on macos

**Comment by C0D3Giant** [comment]
almost forgotten this

[I] [JAVA] Version: 16.0.1
[W] Shader shaders/mesh.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/default.vert | shaders/blockbuild.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/shield.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/buildbeam.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/default.vert | shaders/unitbuild.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/default.vert | shaders/darkness.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/light.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/water.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/space.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/planet.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/planetgrid.vert | shaders/planetgrid.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/atmosphere.vert | shaders/atmosphere.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/unlit.vert | shaders/planet.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/screenspace.vert | shaders/screenspace.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[I] Loaded mod 'Invincible Cheat Mod v6' in 40.4453ms
[I] Loaded mod 'aeromindustry' in 9.9169ms
[I] Loaded mod 'dev-mode' in 2.0394ms
[I] Loaded mod 'Vanilla Enhanced' in 3.3769ms
[I] Loaded mod 'prog-mats' in 17.229ms
[I] Loaded mod 'braindustry' in 16.504ms
[I] Loaded mod 'hackustry' in 8.7603ms
[I] Loaded mod 'betamindy' in 14.793ms
[I] Loaded mod 'time-control' in 1.7049ms
[I] Loaded mod 'multi-lib' in 1.7854ms
[I] Time to initialize modded scripts: 896.18
[I] Total time to load: 8023ms
[W] Shader bloomshaders/screenspace.vert | bloomshaders/bloom.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader bloomshaders/screenspace.vert | bloomshaders/threshold.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader bloomshaders/blurspace.vert | bloomshaders/gaussian.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[W] Shader shaders/cubemap.vert | shaders/cubemap.frag:
Vertex shader
WARNING: 0:2: '' :  #version directive missing

Fragment shader:
WARNING: 0:5: '' :  #version directive missing


[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v7.json
[I] Fetched 11 community servers.

**Comment by QmelZ** [comment]
it doesn't seem like anything is wrong, i can't really fix this. maybe try on a newer/older version?
